# -*- coding: utf-8 -*-
"""CapstoneProject_A25-CS307 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cH1KXlwT8r9A8x9_tjOBGQ5Jd2-njJxG

### Import Library
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.mixture import GaussianMixture
from yellowbrick.cluster import KElbowVisualizer
from sklearn.metrics import silhouette_score
from datetime import datetime
import joblib

"""### Load dataset"""

df = pd.read_csv('customer_segmentation.csv')

print(df.shape)
df.head()

df.info()

df.describe()

"""### Preprocessing"""

df.isnull().sum()

df.duplicated().sum()

# Hapus baris dengan CustomerID atau InvoiceDate kosong
df = df.dropna(subset=['CustomerID', 'InvoiceDate'])

"""### Konversi Tipe Data & Hitung TotalSales"""

# Konversi tanggal dan pastikan kolom numerik valid
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
for col in ['Quantity', 'UnitPrice']:
  df[col] = pd.to_numeric(df[col], errors='coerce')

# Hitung nilai transaksi
df['TotalSales'] = df['Quantity'] * df['UnitPrice']
df[["Quantity","UnitPrice","TotalSales"]].head()

# Drop kolom index jika ada
if 'index' in df.columns:
    df.drop(columns=['index'], inplace=True)

"""### Isi Missing Values & Hapus Duplikat"""

# Mengisi nilai hilang numerik dengan median & kategorikal dengan modus
num_cols = df.select_dtypes(include=[np.number]).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

for col in df.select_dtypes(include='object').columns:
  df[col] = df[col].fillna(df[col].mode().iloc[0])

df = df.drop_duplicates()
print('Setelah cleaning:', df.shape)

df.isnull().sum()

"""### EDA: Tren Penjualan Bulanan"""

df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])
df["Month"] = df["InvoiceDate"].dt.to_period("M")

monthly_sales = df.groupby("Month")["TotalSales"].sum()

ax = monthly_sales.plot(figsize=(10,5), linewidth=2, marker='o')
ax.set_title("Tren Penjualan Bulanan", fontsize=14)
ax.set_xlabel("Bulan")
ax.set_ylabel("Total Penjualan")
plt.xticks(rotation=45)
plt.grid(True, linestyle='--', alpha=0.3)
plt.tight_layout()
plt.show()

"""### Perhitungan RFM"""

# Menghitung Recency, Frequency, Monetary
ref_date = df['InvoiceDate'].max() + pd.Timedelta(days=1)

rfm = df.groupby('CustomerID').agg({
'InvoiceDate': lambda x: (ref_date - x.max()).days,
'InvoiceNo': 'nunique',
'TotalSales': 'sum',
}).reset_index()

rfm.columns = ['CustomerID','Recency','Frequency','Monetary']
rfm.head()

"""### Scaling RFM"""

# Menstandarkan RFM agar K-Means bekerja optimal
scaler = StandardScaler()
scaled_rfm = scaler.fit_transform(rfm[["Recency","Frequency","Monetary"]])

scaled_rfm[:5]

"""### Elbow Method & Silhouette Score"""

# Menentukan jumlah cluster terbaik
model = KMeans(random_state=42)
visualizer = KElbowVisualizer(model, k=(2,10))
visualizer.fit(scaled_rfm)
visualizer.show()

k_optimal = visualizer.elbow_value_
print("k optimal:", k_optimal)

sil_scores = {}
for k in range(2,11):
    km = KMeans(n_clusters=k, random_state=42)
    labels = km.fit_predict(scaled_rfm)
    sil_scores[k] = silhouette_score(scaled_rfm, labels)

sil_scores

"""### Train KMeans Final"""

# Melatih model KMeans dengan k yang dipilih
k = int(k_optimal) if k_optimal else 4
kmeans = KMeans(n_clusters=k, random_state=42)

rfm["Cluster"] = kmeans.fit_predict(scaled_rfm)

joblib.dump(kmeans, "kmeans_rfm_model.joblib")
joblib.dump(scaler, "scaler_rfm.joblib")

rfm.head()

"""### Visualisasi RFM"""

# pairplot untuk melihat pola cluster
sample = rfm.sample(n=min(600, len(rfm)), random_state=42)
sns.pairplot(sample[['Recency','Frequency','Monetary','Cluster']], hue='Cluster')
plt.show()

# Boxplot
rfm_melted = pd.melt(rfm, id_vars=['Cluster'], value_vars=['Recency','Frequency','Monetary'])
sns.boxplot(data=rfm_melted, x='variable', y='value', hue='Cluster')
plt.show()

"""### Summary Cluster"""

# Ringkasan cluster untuk analisis
cluster_summary = rfm.groupby("Cluster").agg({
    "Recency":"mean",
    "Frequency":"mean",
    "Monetary":"mean",
    "CustomerID":"count"
}).rename(columns={"CustomerID":"Count"})

cluster_summary

"""### Interpretasi & Insight Pemasaran"""

cluster_labels = {
    0: "Loyalists - sering membeli & nilai tinggi",
    1: "At Risk - jarang transaksi baru-baru ini",
    2: "Big Spenders - nilai transaksi besar",
    3: "New Customers - pelanggan baru"
}

rfm['Segment'] = rfm['Cluster'].map(cluster_labels)
rfm

print("=== INTERPRETASI SEGMENTASI ===")
for c, label in cluster_labels.items():
    print(f"\nCluster {c} → {label}")

    if "Loyalists" in label:
        print("- Program loyalitas & reward eksklusif.")
    elif "At Risk" in label:
        print("- Promo re-engagement, reminder email, comeback voucher.")
    elif "Big Spenders" in label:
        print("- Produk premium, personalisasi layanan, VIP support.")
    elif "New Customers" in label:
        print("- Welcome promo, edukasi produk, follow up pembelian.")